language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk8

stages:
  - name: format
  - name: test
  #- name: release
    #if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    #- stage: format
      #script: sbt scalafmt::test
    - stage: test
      script:
        - sbt ++$TRAVIS_SCALA_VERSION clean coverage +coreJVM/test coverageReport
        #- sbt validateScalafmt
        #- sbt example/compile
    #- stage: release
      #script: sbt ci-release
